In [4]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.5052, 0.6562, 0.6404],
        [0.6386, 0.3633, 0.0812],
        [0.5819, 0.8355, 0.0227],
        [0.7552, 0.5843, 0.1375],
        [0.9157, 0.7153, 0.4758]])


In [2]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [5]:
if torch.cuda.is_available():
    print("GPU available")
else:
    print("You broke.......HahahahahaHHHAaaaAHHhhha!!!!!!!")

You broke.......HahahahahaHHHAaaaAHHhhha!!!!!!!


In [3]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
